#include: package:flutter_lints/flutter.yaml
include: package:lints/recommended.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    prefer_const_constructors: false
    avoid_print: false
    slash_for_doc_comments: false
    prefer_const_literals_to_create_immutables: false
    prefer_typing_uninitialized_variables: false
    #must_be_immutable: false
    non_constant_identifier_names: false
    # file_names: false
    # public_member_api_docs: false
    # lines_longer_than_80_chars: false
    # avoid_catches_without_on_clauses: false
    # avoid_equals_and_hash_code_on_mutable_classes: false
    # prefer_relative_imports: false
    # type_annotate_public_apis: false
    # avoid_types_on_closure_parameters: false
    # sort_constructors_first: false
    # prefer_generic_function_type_aliases: true
    unnecessary_lambdas: true
    # use_key_in_widget_constructors: false

