package com.v.module_database.realm.model;

//import io.realm.RealmObject;
//import io.realm.annotations.Ignore;

/**
 * https://codeleading.com/article/73763610221/
 * <p>
 * ClassName: User
 * Description: Model类只要继承RealmObject即可.
 *
 * @author zhuming
 * @package_name com.v.module_database.realm
 * @date 2023/9/17 11:23
 */

/**
 * 1、字段类型:
 * Model类中可以包含的字段类型包括基本数据类型(及它们的装箱类型)和Date类, 另外也可以包含RealmObject的子类或者是RealmList<? extends RealmObject>.
 *
 * 2、字段性质:
 * 在字段上加注解可以定义字段的性质:
 *
 * @Required表明字段非null.
 * 原生类型和RealmList类型默认是非null的.
 * RealmObject字段永远是可以为null的.
 *
 * @Ignore表示字段不会被存储.
 *
 * @Index加索引.
 *
 * @PrimaryKey加主键, 主键只能有一个, 主键默认加索引.
 *
 * 但是注意主键默认没有加@Required, 如果主键要求非null, 需要显式添加@Required.
 */
public class User /*extends RealmObject*/ {
    private int user_id;
    private String name;
    private int age;

    public User(int user_id, String name, int age) {
        this.user_id = user_id;
        this.name = name;
        this.age = age;
    }

//    @Ignore
    private int sessionId;

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    // Standard getters & setters generated by your IDE…
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public int getSessionId() {
        return sessionId;
    }

    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }
}


